<?php 
/************************************************************************/
/* iSelf                                                                */
/************************************************************************/
/************************************************************************/
/* This file was generated by the iSelf M@xLearn 2.0 installation script.*/
/* File generated 2005-03-03 15:03:05                                   */
/************************************************************************/
/************************************************************************/

/* the database user name                                               */
define('DB_USER',                      'course');

/* the database password                                                */
define('DB_PASSWORD',                  'txy56@9');

/* the database host                                                    */
//define('DB_HOST',                      '158.108.216.13');
define('DB_HOST',                      'localhost');

/* the database tcp/ip port                                             */
define('DB_PORT',                      '3306');

/* the database name                                                    */
define('DB_NAME',                      'course');

define('DB_TYPE',                      'mysql');

//define('DB_DSN',                      'mysql://course:txy56@9@158.108.216.13/course');
define('DB_DSN',                      'mysql://course:txy56@9@localhost/course');
		
/* The prefix to add to table names to avoid conflicts with existing    */
/* tables. Default:                                                     */
define('TABLE_PREFIX',                 '');

/* your (ATutor system admin) username to let you add new instructors   */
define('ADMIN_USERNAME',               'admin');


/* your (ATutor system admin) password to let you add new instructors   */
define('ADMIN_PASSWORD',               'admin');

/* your (admin) email address                                           */
define('ADMIN_EMAIL',                  'admin@iself.biz');

/* do you want to receive emails when new instructor accounts           */
/* require approval                                                     */
//define('EMAIL_NOTIFY',                 );

/* allow regular account users to request their account to be           */
/* upgraded to instructor accounts.                                     */
//define('ALLOW_INSTRUCTOR_REQUESTS',    );

/* If ALLOW_INSTRUCTOR_REQUESTS is true then you can have the           */
/* requests approved instantly, otherwise each request will             */
/* have to be approved manually by the admin.                           */
//define('AUTO_APPROVE_INSTRUCTORS',     );

/************************************************************************/
/* File manager options:                                                */

/* Default maximum allowable file size in Bytes to upload:              */
/* Will not override the upload_max_filesize in php.ini                 */
$MaxFileSize   =   1048576; /* 1 MB */

/* Default total maximum allowable course size in Bytes:                */
/* When this number is exceeded, no more uploads will be allowed        */
$MaxCourseSize =  10485760; /* 10 MB */

/* Soft limit threshold:                                                */
/* How much a course can be over, while still allowing the              */
/* upload to finish.                                                    */
/* Therefore the real course limit is                                   */
/* $MaxCourseSize + $MaxCourseFloat, but when the float gets          */
/* used then no more uploads will be allowed.                           */
$MaxCourseFloat =  2097152; /* 2 MB */

/* Illegal file types, by extension. Include any extensions             */
/* you do not want to allow for uploading. (Just the extention          */
/* without the leading dot.)                                            */
//$IllegalExtentions = array('', );

/* The name of your course website.                                     */
/* Example: Acme University's Course Server                             */
/* Single quotes will have to be escaped with a slash: \'.              */
define('SITE_NAME',						'Course Server');

/* Public area variables.   */
/* Top left header image  - approximately w:230 x h:90					*/
/* Default: images/pub_default.jpg										*/	
define('HEADER_IMAGE',					'images/pub_default.jpg');

/* Top right logo default: images/at-logo.gif */
define('HEADER_LOGO',					'images/at-logo.gif');

/* link for the 'home' menu item.  Will not show if empty */
define('HOME_URL',						'');

define('PATH',						'lms');

define('REALPATH',						'/data/httpd_course/html/uat_lms');

define('FILEPATH',						'/data/httpd_course/files');

/* Default language to use, if not browser-defined or                   */
/* user-defined. 'en' is always available. Any other language           */
/* specified must already exist in the database.                        */
/* Default language: en                                                 */
define('DEFAULT_LANGUAGE',             'en');

/* DO NOT ALTER THIS LAST LINE                                          */
define('AT_INSTALL', true);

?>
